version: '3.9'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product-mabagement
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice-product-management
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs:/app/logs
  zipkin:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin
    restart: always
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
